#!/usr/bin/env python

"""
The purpose of this qualification is to exclude people who have participated in
this or a similar study.
"""

import mturk

import logger

options = {
    'Name': 'qualification21_autogranted',
    'Description': 'This qualification cannot be requested. It is assigned automatically.',
    'QualificationTypeStatus': 'Active'
}

m = mturk.MechanicalTurk()
response = m.request('CreateQualificationType', options)
logger.debug(response)

qualification_id = response['CreateQualificationTypeResponse']['QualificationType']['QualificationTypeId']
print(qualification_id)
