#!/usr/bin/env python

import sys

import mturk

qualification_id = sys.argv[1]

question = '''<?xml version="1.0"?>
<ExternalQuestion xmlns="http://mechanicalturk.amazonaws.com/AWSMechanicalTurkDataSchemas/2006-07-14/ExternalQuestion.xsd">
    <ExternalURL>https://www.surveygizmo.com/s3/3034691/survey</ExternalURL>
    <FrameHeight>1000</FrameHeight>
</ExternalQuestion>
'''

options = {
    'Title': 'Take a five-minute personality test!',
    'Description': 'Answer two dozen questions about your decision-making style.',
    'Question': question,
    'Reward': [{
        'Amount': 0.25,
        'CurrencyCode': 'USD'
    }],
    'AssignmentDurationInSeconds': 60*60,
    'LifetimeInSeconds': 60*60*24*14,
    'MaxAssignments': 10,
    'Keywords': 'survey, personality',
    'QualificationRequirement': [{
        'QualificationTypeId': qualification_id,
        'Comparator': 'DoesNotExist',
        'RequiredToPreview': 'true'
    }, {
        'QualificationTypeId': mturk.LOCALE,
        'Comparator': 'EqualTo',
        'LocaleValue': {
            'Country': 'US'
        },
        'RequiredToPreview': 'true'
    }, {
        'QualificationTypeId': mturk.P_APPROVED,
        'Comparator': 'GreaterThan',
        'IntegerValue': 95,
        'RequiredToPreview': 'true'
    }]
}

m = mturk.MechanicalTurk()
r = m.request('CreateHIT', options)
print(r)
