#!/usr/bin/env python3

import sys

import mturk

hit_id = sys.argv[1]

m = mturk.MechanicalTurk()

r = m.request('ForceExpireHIT', {'Operation': 'ForceExpireHIT', 'HITId': hit_id})
print(r)
r = m.request('DisposeHIT', {'Operation': 'DisposeHIT', 'HITId': hit_id})
print(r)
