#!/usr/bin/env python

"""
Get all workers whose HIT attempts have been approved and write them to a file
(one on each line)
"""

import sys

import turk_common
import logger

STATUS = 'Approved'

def worker_id_from_assignments(assignments):
    for assignment in assignments:
        yield assignment['WorkerId']

def main(filename, hit):
    with open(filename, 'w') as output:
        assignments = turk_common.get_assignments(hit, STATUS)
        workers = worker_id_from_assignments(assignments)

        for worker in workers:
            output.write("%s\n" % worker)

if __name__ == '__main__':
    if len(sys.argv) < 3:
        logger.critical('usage: %s output_filename hit_id' % sys.argv[0])
        sys.exit(1)

    filename = sys.argv[1]
    hit = sys.argv[2]

    main(filename, hit)
