#!/usr/bin/env python

"""
Summarize HIT status
"""

import sys

import turk_common
import logger

def worker_id_from_assignments(assignments):
    for assignment in assignments:
        yield assignment['WorkerId']

def get_number_of_assignments(hit_id, status):
    response = turk_common.turk.request('GetAssignmentsForHIT', {
            'HITId': hit_id,
            'AssignmentStatus': status})
    result = response['GetAssignmentsForHITResponse']['GetAssignmentsForHITResult']
    return int(result['TotalNumResults'])

def main(hit_id):
    total = 0
    for status in ['Submitted', 'Approved', 'Rejected']:
        assignments = get_number_of_assignments(hit_id, status)
        total += assignments
        print('%s: %s' % (status, assignments))

    print('Total submitted: %d' % total)

    response = turk_common.turk.request('GetHIT', {
            'HITId': hit_id,
            'AssignmentStatus': status})
    max_assignments = response['GetHITResponse']['HIT']['MaxAssignments']
    print('Max assignments: %s' % max_assignments)

if __name__ == '__main__':
    if len(sys.argv) < 2:
        logger.critical('usage: %s hit_id' % sys.argv[0])
        sys.exit(1)

    hit = sys.argv[1]

    main(hit)
