#!/usr/bin/env python

"""
Summarize HIT status
"""

import sys

import turk_common
import logger

def worker_id_from_assignments(assignments):
    for assignment in assignments:
        yield assignment['WorkerId']

def get_number_of_assignments(hit_id, status):
    response = turk_common.turk.request('GetAssignmentsForHIT', {
            'HITId': hit_id,
            'AssignmentStatus': status})
    result = response['GetAssignmentsForHITResponse']['GetAssignmentsForHITResult']
    return result['TotalNumResults']

def main(hit):
    for status in ['Submitted', 'Approved', 'Rejected']:
        assignments = get_number_of_assignments(hit, status)
        print('%s: %s' % (status, assignments))

if __name__ == '__main__':
    if len(sys.argv) < 2:
        logger.critical('usage: %s hit_id' % sys.argv[0])
        sys.exit(1)

    hit = sys.argv[1]

    main(hit)
