#!/usr/bin/env python

"""
Print only lines that appear in both of the given files
"""

import argparse


def intersect(filename1, filename2):
    with open(filename1, 'r') as file1:
        with open(filename2, 'r') as file2:
            lines1 = file1.readlines()
            lines2 = file2.readlines()
            intersection = set(lines1).intersection(set(lines2))
            for line in intersection:
                print(line, end='')


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('file1')
    parser.add_argument('file2')
    args = parser.parse_args()
    intersect(args.file1, args.file2)


if __name__ == '__main__':
    main()
