#!/usr/bin/env python

"""
Lists everyone who has the given qualification
"""

import sys

import xmltodict

import turk_common
import logger

def get_qualifications(qualification_id):
    page = 1
    results_available = True
    while results_available:
        response = turk_common.turk.request('GetQualificationsForQualificationType', {
                'QualificationTypeId': qualification_id,
                'Status': 'Granted',
                'PageSize': 100,
                'PageNumber': page})

        result = response['GetQualificationsForQualificationTypeResponse']['GetQualificationsForQualificationTypeResult']
        logger.debug(result)
        num_results = int(result['NumResults'])
        results_available = num_results > 0

        if results_available:
            qualifications = result['Qualification']
            if num_results == 1:
                yield qualifications
            else:
                for qualification in qualifications:
                    yield qualification

        page += 1


def workers_with_qualifications(qualifications):
    workers = set()
    for qualification in qualifications:
        workers.add(qualification['SubjectId'])
    return workers

def main(qualification):
    qualifications = get_qualifications(qualification)
    already_granted = workers_with_qualifications(qualifications)

    for worker in already_granted:
        print(worker)

if __name__ == '__main__':
    if len(sys.argv) < 2:
        logger.critical('usage: %s qualification_id' % sys.argv[0])
        sys.exit(1)

    qualification = sys.argv[1]

    main(qualification)
