#!/usr/bin/env python

"""
List qualifications
"""

from pprint import pprint

import mturk
import logger

logger.init('info')


class ListQualificationsScript(mturk.MTurkScript):
    """
    List qualifications
    """

    def run(self):
        response = self.client.list_qualification_types(
            MustBeOwnedByCaller=True,
            MustBeRequestable=False
        )
        pprint(response)


if __name__ == '__main__':
    ListQualificationsScript().run()
