#!/usr/bin/env python

"""
Subtract the lines in the second file from the lines in the first file
"""

import argparse


def subtract(filename1, filename2):
    with open(filename1, 'r') as file1:
        with open(filename2, 'r') as file2:
            lines1 = file1.readlines()
            lines2 = file2.readlines()
            difference = set(lines1) - set(lines2)
            for line in difference:
                print(line, end='')


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('file1')
    parser.add_argument('file2')
    args = parser.parse_args()
    subtract(args.file1, args.file2)


if __name__ == '__main__':
    main()
